### ISSUE TITLE
Measure external arc of 154-240

### ISSUE THREAD

**Issue by will-henney** [will-henney/ll-catalog-papers#37]
> Sí, está faltando el objecto 154-240. Noté que para este objeto sólo trazamos el arco interno. Entonces revisando los script que hacen las figuras, percibí que hay una máscara:

> m = np.isfinite(tab['R_out']) & np.isfinite(tab['R_in']) & (tab['R_out'] > tab['R_in'])

> Por lo que este objeto es descartado.

_Originally posted by @AngelGSoto in https://github.com/will-henney/ll-catalog-papers/issues/36#issuecomment-1127202577_

**Comment by will-henney** [comment]
The arc looks thin in the F555W filter, which is probably dominated by [O III]. We could either measure it there, or maybe look at the wfpc2 f502n filter, although I don't know if we have an aligned version that covers this region

**Comment by will-henney** [comment]
I am a bit concerned about the arc fits:
![CleanShot 2022-05-29 at 14 03 30](https://user-images.githubusercontent.com/161264/170887352-833b3104-d556-4f37-b349-82f0d0378719.jpg)

It doesn't look like the circle fits pass through the points very well. Could you please re-check this @AngelGSoto

**Comment by AngelGSoto** [comment]
I have revised the circle fits.  The outer circle fit was improved by adding more points to trace the arc. However, the inner circle fit continues the same.  I'm unsure what we can do to improve the fit of the inner arc.

![image](https://user-images.githubusercontent.com/16337679/173243435-73809471-8add-4038-ad40-6dabb7e2f16e.png)

**Comment by will-henney** [comment]
I think there is a parameter `delta_theta` that you could try adjusting. Maybe it would work better with 90 deg

**Comment by AngelGSoto** [comment]
The arc fits for this object were fixed

![image](https://user-images.githubusercontent.com/16337679/174117472-1726e9ae-ad78-4de3-8266-90afedf28f57.png)

The problem was that we were considering the old methodology of the lmfit package on fit-circle-shell.py.

**Comment by will-henney** [comment]
The new fits look much better!  Could you please also add the new figures to the paper

**Comment by will-henney** [comment]
Fixed by #41

**Comment by will-henney** [comment]
Which version of circle_fit are you using?  I seem to remember that these
type of problems largely went away with more recent versions


  Dr William Henney, Instituto de Radioastronomía y Astrofísica,
  Universidad Nacional Autónoma de México, Campus Morelia
