### ISSUE TITLE
Add new source that Luis found just S of LL 7

### ISSUE THREAD

**Issue by will-henney** [will-henney/ll-catalog-papers#5]
Original message from Luis Ángel

<img width="1089" alt="Screen Shot 2020-08-31 at 12 44 27" src="https://user-images.githubusercontent.com/161264/91749843-b94a7b80-eb87-11ea-9d70-ca2d28b9b459.png">

We need to decide which image to use for this.  It is in ACS `strip7l` of Robberto, and should be in WFPC2 field 64 or 78.  It is outside the field of Bally observations.

**Comment by will-henney** [comment]
Luis is going to trace the outer arc on the Robberto ACS image.  The S/N is too low in the WFPC2 images.  The inner arc cannot be seen.

**Comment by AngelGSoto** [comment]
I have traced the outer arc of this source. The object was designated 364-411.
