### ISSUE TITLE
Coincidence of arcs with stellar sources

### ISSUE THREAD

**Issue by will-henney** [will-henney/ll-catalog-papers#9]
Luis should describe where the tables of this information are.

**Comment by AngelGSoto** [comment]
I searched for the stellar component of each source on Simbad using Astroquery. The search was done using several radii. The resulting tables are in the Dropbox folder:

  1. LuisBowshocks/Simbad/arcs-summary-unique.escv. Here I used a radii of 0.30 arcsec
  2. LuisBowshocks/Simbad/ll-stars-arcs-simbad-047.ecsv. Here I used a radii of 0.47
  3. LuisBowshocks/Simbad/ll-stars-arcs-simbad-053.ecsv. Here I used a radii of 0.50

"ll-stars-arcs-simbad-053.ecsv" is the best result, almost all our sources are there. 

The tables of the coincidence of arcs with stellar sources in the different catalogs are in:

    -) LuisBowshocks/Robberto2005/arc-stellar-robberto.csv
    -) LuisBowshocks/Robberto2010/arc-stellar-RSS2010.csv
    -) LuisBowshocks/Robberto2013/arc-stellar-robberto2013.csv
    -) LuisBowshocks/Morales-Calderon2011/arc-stellar-morales2011.csv
    -) LuisBowshocks/Hillenbrand2000/arc-stellar-hillenbrand2000.csv
    -) LuisBowshocks/COUP/Getman2005/arc-stellar-getman2005.csv
    -) LuisBowshocks/Smith2005/arc-stellar-smith2005.csv

I realized that I have yet to find the stellar matches in some other catalogs. I'll work on that!

**Comment by will-henney** [comment]
I added the Simbad files to the other repo https://github.com/will-henney/orion-bowshock-catalog/commit/0b75d6bda69ff616e769527e25cefe64b52ab073

**Comment by will-henney** [comment]
@AngelGSoto you should add the program that generated these files.  

Also, we need to filter out simbad matches that are not stars.   Anything that is classified as ISM needs to be dropped.  Most of these are the arcs themselves, for instance from the BOM paper.

**Comment by will-henney** [comment]
I have regenerated the table of coincidences with miscellaneous catalogs.  It is in the other repo as arc-stellar-sources.ecsv 

Nearly every arc has an associated star from the Robberto 2013 or 2010 catalogs.

**Comment by will-henney** [comment]
Luis has now added the SIMBAD sources to the tables.  However, these come from a great variety of sources, which I don't think is ideal.  Here is an example:

![CleanShot 2021-08-10 at 09 18 01@2x](https://user-images.githubusercontent.com/161264/128883487-2fd44437-228c-40bb-b549-741c5d39a9e5.jpg)

As an alternative, we should  try adding sources from the two Robberto catalogs, as mentioned above.

**Comment by will-henney** [comment]
Luis has now finished this and added the Robberto sources to the tables
